#! /bin/bash
# Copyright (c) 1000-2014 FPT.
# All rights reserved.
# *IMPORTANT*
# you need to set PPPOE_AREA and PPPOE_IFACE below
# copy this to /etc/init.d/ and chmod +x it
# set auto start with update-rc.d pppoed defaults
# by default it will start on 3 and 5
# Author: CongNT3, 2014
#
# /etc/init.d/pppoed
#
### BEGIN INIT INFO
# Provides: pppoed
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: PPPoE checker daemon
# Description:   Automated PPPoE checker daemon process
### END INIT INFO

# Activate the python virtual environment
    . /root/python/bin/activate
    export PPPOE_AREA="HCM"
    export PPPOE_IFACE="eth0"

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python /opt/pppoe-checker/Modules/pppdaemon.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /opt/pppoe-checker/Modules/pppdaemon.py stop
    ps -ef | grep pppdaemon.py | grep -v grep | awk '{print $2}' | xargs kill -9
    ;;
  restart)
    echo "Restarting server"
    python /opt/pppoe-checker/Modules/pppdaemon.py stop
    ps -ef | grep pppdaemon.py | grep -v grep | awk '{print $2}' | xargs kill -9
    python /opt/pppoe-checker/Modules/pppdaemon.py start
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/pppoed {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
